server {
    # Nginx écoute sur le port 80 pour les requêtes HTTP
    # Toutes les requêtes seront passé au travers de ce serveur. On peut les voir dans les logs d'accès de Nginx (access.log)
    listen 80;
    server_name _; # Accepte toutes les requêtes (wildcard). Il faudrait peut-être le changer

    client_max_body_size 10m;

    # Cette emplacement est utilisé pour les vérifications de santé (health checks) de Nginx
    location = /nginx-health {
        access_log off;
        add_header Content-Type text/plain;
        return 200 "Le service est en ligne\n";
    }

    location /api/ {
        proxy_pass http://api:8000/; # Transfère les requêtes API vers l'application FastAPI
        proxy_http_version 1.1; # Utilise HTTP/1.1 pour supporter les connexions persistantes et WebSockets

        proxy_set_header Host $host; # Préserve l'en-tête Host original
        proxy_set_header X-Real-IP $remote_addr; # Transmet l'IP originale du client
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # Ajoute l'IP du client
        proxy_set_header X-Forwarded-Proto $scheme; # Informe FastAPI du protocole original (HTTP/HTTPS)
        proxy_set_header X-Forwarded-Host $host; # Informe FastAPI de l'hôte original
        proxy_set_header X-Forwarded-Port $server_port; # Informe FastAPI du port original

        proxy_set_header Upgrade $http_upgrade; # Supporte les mises à niveau de protocole (WebSockets)
        proxy_set_header Connection "upgrade"; # Supporte les connexions persistantes et WebSockets

        proxy_connect_timeout 30s; # Temps d'attente maximale pour établir une connexion avec le backend
        proxy_send_timeout 120s; # Temps d'attente maximale pour envoyer une requête au backend
        proxy_read_timeout 120s; # Temps d'attente maximale pour lire la réponse du backend
    }

    location / {
        proxy_pass http://frontend:5173; # Transfère les requêtes vers le frontend React
        proxy_http_version 1.1; # Utilise HTTP/1.1 pour supporter les connexions persistantes et WebSockets

        proxy_set_header Host $host; # Préserve l'en-tête Host original

        proxy_set_header Upgrade $http_upgrade; # Supporte les mises à niveau de protocole (WebSockets)
        proxy_set_header Connection "upgrade"; # Supporte les connexions persistantes et WebSockets
    }
}
